### PR TITLE
Added Head-hover effects, Stars background and planet animations.

### PR DESCRIPTION
**Pull request by adsingh14**
Added CSS animations.

### CODE REVIEW

**Review by celinakhalife — COMMENTED** [review]
hey @adsingh14 , were `package.json` and `package-lock.json` removed by mistake? or is there any reason we don't want them in the project?

**Comment by adsingh14** [comment]
@celinakhalife I'll add it in my next commit.

**Review by adsingh14 — COMMENTED** [review]
Synced with master.

**Review by celinakhalife — APPROVED** [review]
Looks great!! Thank you!

**Pull request merged**
